const menu = [
    {
      id: 1,
      category: "İçecekler",
      subcategory: "Sıcak Kahve",
      title: "Türk Kahvesi",
      desc: "Türk kahvesi, binlerce yıllık gelenekleri modern lezzetle buluşturan eşsiz bir deneyim sunuyor. İnce köpüğü ve yoğun aromasıyla her bir yudumu tarihin ve lezzetin derinliklerine götürüyor. Bir fincan Türk kahvesi, geçmişle günümüzü buluşturan, kişiselleştirilmiş bir huzur anıdır; hem sıcak bir sohbete eşlik ederken hem de kendi içsel yolculuğunuzu desteklerken size eşlik ediyor.",
      price: 10,
      img: "./images/cay.jpg",
    },
    {
      id: 2,
      category: "İçecekler",
      subcategory: "Sıcak Kahve",
      title: "Spesyal Şehzade",
      desc: "Misafirlerimize özel bir ayrıcalık sunan özel kahvemiz, tutkulu uzmanların özenle seçtiği en kaliteli kahve çekirdeklerinin özenli bir şekilde harmanlandığı eşsiz bir lezzet sunar. Her bir fincan, dikkatlice işlenmiş çekirdeklerin mükemmel uyumuyla bir araya gelerek zengin bir aroma ve dokunuşla buluşur. İlk yudumda damakta açılan bu lezzet, içinde barındırdığı notalarla özel anıları harekete geçirirken, kaliteli kahvenin benzersizliğini en saf haliyle hissettirir. Bu özel kahve deneyimi, her daim unutulmaz anılara kucak açmak isteyenler için bir davettir.",
      price: 10,
      img: "./images/item-1.jpeg",
    },
    {
      id: 3,
      category: "İçecekler",
      subcategory: "Sıcak Kahve",
      title: "Çilekli Şehzade",
      desc: "Misafirlerimize yaz mevsiminin tazeliğini ve lezzetini sunan özel çilekli kahvemiz, özenle seçilmiş taptaze çileklerin sıcaklığıyla harmanlanan enfes bir deneyim sunuyor. Her bir fincan, çekici çilek notalarının özenle kahveyle buluştuğu, tatlılık ve canlılık arasında mükemmel bir denge yakalayan bir lezzet sunar. İlk yudumda damakta çileğin tazelik ve tatlılığına açılan bu lezzet, yazın renklerini ve enerjisini her bir yudumda hissettirirken, unutulmaz anıların tadını çıkarmanız için sizi bekliyor. Bu özel çilekli kahve, lezzetin ve tazeliğin dansını yaşamak isteyenleri büyüleyici bir yolculuğa davet ediyor.",
      price: 10,
      img: "./images/item-1.jpeg",
    },
    {
      id: 4,
      category: "İçecekler",
      subcategory: "Sıcak Kahve",
      title: "Çikolatalı Şehzade",
      desc: "Misafirlerimize tatlı bir kaçamak sunan özel çikolatalı kahvemiz, seçkin çikolata notalarının özenle seçilmiş kahve çekirdekleriyle buluştuğu büyülü bir lezzet sunuyor. Her bir fincan, zengin kakao aromalarının sıcak kahve ile muhteşem bir uyum içinde dans ettiği, tatlılık ve yoğunluğun mükemmel dengelediği bir deneyim sunar. İlk yudumda damakta açılan bu çikolata rüyası, tatlı ve aromatik bir keyif sunarken, içindeki çikolatanın çekiciliğiyle anıları tatlandırmanız için sizi bekliyor. Bu özel çikolatalı kahve, lezzetin ve tatlılığın kusursuz uyumunu arayanları büyüleyici bir lezzet yolculuğuna çıkarıyor.",
      price: 10,
      img: "./images/item-1.jpeg",
    },
    {
      id: 5,
      category: "İçecekler",
      subcategory: "Sıcak Kahve",
      title: "Granül Sade-Sütlü",
      desc: "Misafirlerimize hem sade hem de süt ile harika bir denge sunan özel granül kahvemiz, seçkin kahve çekirdeklerinin özenle işlenip hazırlanarak elde edilen eşsiz bir lezzeti yansıtıyor. Her bir fincan, sade ve sütün kusursuz birlikteliği ile sizi özgün bir kahve serüvenine davet ediyor. İlk yudumda damakta açılan bu lezzet, kahvenin kendine özgü aromasını korurken, sütün yumuşaklığıyla mükemmel bir denge yakalıyor. Bu özel granül kahve deneyimi, sadece kahve tutkunlarını değil aynı zamanda farklı lezzetleri bir arada yaşamaktan keyif alanları da büyülemek için bekliyor.",
      price: 10,
      img: "./images/item-1.jpeg",
    },
    {
      id: 6,
      category: "İçecekler",
      subcategory: "Sıcak Kahve",
      title: "Filtre Kahve Sütlü-Aromalı",
      desc: "Kahve dünyasında özgün bir serüvene hazır mısınız? Özel filtre kahvemiz, sütün ve sıradışı aromaların gizemli buluşmasını sunuyor. Her bir yudum, kahve çekirdeklerinin ustalıkla filtrelenmiş tadını, kremsi sütün dokunuşuyla birleştiriyor. İlk yudumda damakta açılan bu lezzet, sizi sadece kahvenin dünyasına değil, aynı zamanda tatların ve aromaların büyülü labirentine davet ediyor. Rüya gibi bir lezzet yolculuğuna çıkmaya hazır olun; çünkü bu özel filtre kahve, her yudumda sizi farklı bir öyküye taşıyacak.",
      price: 10,
      img: "./images/item-1.jpeg",
    },
    {
      id: 7,
      category: "İçecekler",
      subcategory: "Soğuk Kahve",
      title: "Soğuk Kahve Sade-Aromalı",
      desc: "Serin bir mola için özel bir davet: Soğuk kahvemiz, sade ve aromaların muhteşem dansını özgün bir şekilde sunuyor. Her bir yudum, ferahlatıcı soğuk kahvenin lezzetini ve sıra dışı aromaların büyüsünü içinde taşıyor. İlk yudumda damakta hissedilen serinlik, ardından açılan tatlarla birleşerek sizi ferahlatan bir lezzet patlaması sunuyor. Bu özel soğuk kahve deneyimi, hem klasik kahve severleri hem de yeni tatlar arayanları büyüleyici bir lezzet yolculuğuna çıkarıyor.",
      price: 10,
      img: "./images/item-1.jpeg",
    },
    {
      id: 8,
      category: "İçecekler",
      subcategory: "Çaylar",
      title: "Çay",
      desc: "Doğanın sakinliğini bardağınızda bulacağınız özel çayımız, seçkin yaprakların huzurunu sunuyor. Her bir yudum, zarif çay notalarının ve hafif aromaların dengeli bir birleşimini taşıyor. İlk yudumda damakta açılan bu hafif lezzet, sizi içten bir keyif anına davet ediyor. Bu özel çay deneyimi, hem geleneksel çayı sevenler hem de sakin bir mola arayanlar için ideal bir seçenek.",
      price: 10,
      img: "./images/item-1.jpeg",
    },
    {
      id: 9,
      category: "İçecekler",
      subcategory: "Soğuk İçecekler",
      title: "Ayran",
      desc: "Serinliği ve ferahlığı bir araya getiren özel ayranımız, sıcak günlerde rahatlamak isteyenler için mükemmel bir seçenek. Doğal yoğurdun lezzetiyle buluşan tazelik, her bir yudumda damakta ferahlatıcı bir serinlik bırakıyor. Ayranımız, sade ve içten lezzetiyle içeceğiniz anı özel kılıyor, sizi serinletiyor ve enerji veriyor. Bu özel ayran deneyimi, sadece bir içecek değil aynı zamanda bir ferahlık anıdır.",
      price: 10,
      img: "./images/item-1.jpeg",
    },
    {
      id: 10,
      category: "İçecekler",
      subcategory: "Soğuk İçecekler",
      title: "Limonata",
      desc: "Taze bir esintiyi bardağınıza taşıyan özel limonatamız, doğal limonun ferahlatıcı tadını sunuyor. Her bir yudum, limonun canlandırıcı asiditesiyle serinletici bir denge yakalıyor. İlk yudumda damakta açılan tazelik, içeceğiniz anı adeta bir nefes alma anına dönüştürüyor. Limonatanın hafif ve lezzetli dokusu, sıcak günlerde serinlemek veya anın tadını çıkarmak isteyenler için mükemmel bir seçenek sunuyor.",
      price: 10,
      img: "./images/item-1.jpeg",
    },
    {
      id: 11,
      category: "İçecekler",
      subcategory: "Soğuk İçecekler",
      title: "Çilekli Limonata",
      desc: "Yazın renklerini bardağınıza taşıyan özel çilekli limonatamız, doğanın tatlılığını ve ferahlığını bir araya getiriyor. Doğal çileklerin tatlılığıyla limonun ferahlatıcı dokusu buluşuyor. Her bir yudum, tatlı ve ekşi notaların dansını damakta hissettiriyor. İlk yudumda açılan bu lezzet, sizi mevsimin enerjisiyle sararken içeceğiniz anı özel kılıyor. Çilekli limonatamız, serinlemenin ve tatların büyülü bir karışımını arayanları lezzet dolu bir yolculuğa davet ediyor.",
      price: 10,
      img: "./images/item-1.jpeg",
    },
    {
      id: 12,
      category: "İçecekler",
      subcategory: "Çaylar",
      title: "Karadut Çayı",
      desc: "Doğanın gizemli tatlarına bir keşif yapmaya hazır mısınız? Özel karadut çayımız, enfes karadut meyvesinin doğallığını ve zengin aromasını sunuyor. Her bir yudum, tatlı ve hafif ekşiliğin dansını damakta hissettiriyor. İlk yudumda açılan bu lezzet, sizi tatlı bir serüvene davet ederken içeceğiniz anı anlamlı kılıyor. Karadut çayımız, farklı ve eşsiz bir içecek deneyimi arayanları doğanın en güzel armağanlarından biriyle tanışmaya davet ediyor.",
      price: 10,
      img: "./images/item-1.jpeg",
    },
    {
      id: 13,
      category: "İçecekler",
      subcategory: "Çaylar",
      title: "Elma Çayı",
      desc: "Doğanın tatlı armağanlarından ilham alan özel elma çayımız, sıcak bir içecekle rahatlamak isteyenlere eşsiz bir lezzet sunuyor. Elmanın tatlılığını ve hafif ekşiliğini taşıyan her bir yudum, sizi huzur dolu bir yolculuğa çıkarıyor. İlk yudumda damakta açılan bu hafif ve doğal lezzet, içeceğiniz anı sadece bir an değil, bir keyif anına dönüştürüyor. Elma çayımız, hem geleneksel çayı sevenleri hem de farklı tatları denemek isteyenleri içsel bir rahatlama ve lezzetli bir deneyime davet ediyor.",
      price: 10,
      img: "./images/item-1.jpeg",
    },
    {
      id: 14,
      category: "İçecekler",
      subcategory: "Çaylar",
      title: "Çilek Çayı",
      desc: "Mevsimin tatlılığını bardağınıza getiren özel çilek çayımız, doğanın taptaze lezzetini sunuyor. Doğal çileklerin tatlılığı ve aromasıyla buluşan her bir yudum, damakta tatlı bir şölen yaratıyor. İlk yudumda hissedilen çilek notaları, içeceğiniz anı adeta bir çilek tarlasında dolaşırken geçirilen bir anıya dönüştürüyor. Çilek çayımız, hem tatlı hem de ferahlatıcı bir lezzet arayanları mevsimin en güzel tattan biriyle tanışmaya davet ediyor.",
      price: 10,
      img: "./images/item-1.jpeg",
    },
    {
      id: 15,
      category: "İçecekler",
      subcategory: "Çaylar",
      title: "Nar Çayı",
      desc: "Doğanın zenginliğini bardağınıza taşıyan özel nar çayımız, narın benzersiz tat ve aroma dünyasını sunuyor. Narın hafif ekşiliği ve tatlılığıyla buluşan her bir yudum, damakta zengin bir lezzet patlaması yaratıyor. İlk yudumda açılan narın benzersiz notaları, içeceğiniz anı adeta bir nar bahçesinde geçirilen bir anıya dönüştürüyor. Nar çayımız, hem taze hem de sofistike bir lezzet arayanları mevsimin en güzel armağanlarından biriyle tanışmaya davet ediyor.",
      price: 10,
      img: "./images/item-1.jpeg",
    },
    {
      id: 16,
      category: "İçecekler",
      subcategory: "Çaylar",
      title: "Kuşburnu Çayı",
      desc: "Doğanın sağlık ve lezzet dolu hediyesi olan özel kuşburnu çayımız, enerji dolu bir içecekle kendinizi şımartmanızı sağlıyor. Doğal kuşburnu meyvesinin özgün tadını ve zengin C vitamini içeriğini sunan her bir yudum, damakta hafif ekşilik ve tatlılık harmonisini taşıyor. İlk yudumda açılan bu taze lezzet, içeceğiniz anı sadece bir mola değil, vücudunuzu ve zihninizi canlandıran bir ritüele dönüştürüyor. Kuşburnu çayımız, hem doğanın mucizesine hem de lezzetin içsel gücüne meraklıları bir sağlık dolu yolculuğa davet ediyor.",
      price: 10,
      img: "./images/item-1.jpeg",
    },
    {
      id: 17,
      category: "İçecekler",
      subcategory: "Soğuk İçecekler",
      title: "Kola",
      desc: "Kahramanın geldiği an: özel kola içeceğimiz, serinlemek ve keyif almak isteyenleri eşsiz bir tat deneyimine davet ediyor. Kahvenin koyuluğuyla karamelin tatlılığının buluştuğu her bir yudum, damakta canlandırıcı ve ferahlatıcı bir lezzet bırakıyor. İlk yudumda hissedilen bu tanıdık lezzet, içeceğiniz anı sadece bir kola içimi değil, keyif dolu bir anıya dönüştürüyor. Özel kola içeceğimiz, hem enerji dolu bir mola arayanları hem de serinlemek isteyenleri ferahlatıcı bir deneyime davet ediyor.",
      price: 10,
      img: "./images/item-1.jpeg",
    },
    {
      id: 18,
      category: "İçecekler",
      subcategory: "Soğuk İçecekler",
      title: "Fanta",
      desc: "Meyve tadının coşkusunu bardağınıza getiren özel Fanta içeceğimiz, enerji dolu bir deneyim sunuyor. Doğal meyve aromalarının ferahlatıcı tatlarıyla buluşan her bir yudum, damakta canlı bir lezzet patlaması yaratıyor. İlk yudumda açılan meyve notaları, içeceğiniz anı sadece bir serinleme anı değil, aynı zamanda tatların renkli dünyasında bir yolculuk anına dönüştürüyor. Fanta içeceğimiz, hem meyve coşkusunu arayanları hem de keyifli anlar yaşamak isteyenleri enerjik bir lezzet yolculuğuna davet ediyor.",
      price: 10,
      img: "./images/item-1.jpeg",
    },
    {
      id: 19,
      category: "İçecekler",
      subcategory: "Soğuk İçecekler",
      title: "Sprite",
      desc: "Taze bir serinliğin anahtarı olan özel Sprite içeceğimiz, hafif ve ferahlatıcı bir deneyim sunuyor. Limonun doğal ferahlığıyla buluşan her bir yudum, damakta canlandırıcı bir tat bırakıyor. İlk yudumda hissedilen bu hafif lezzet, içeceğiniz anı sadece bir serinleme anı değil, aynı zamanda tazelik ve hafiflik dolu bir anıya dönüştürüyor. Sprite içeceğimiz, hem lezzet hem de ferahlık arayanları serinletici bir lezzet yolculuğuna davet ediyor.",
      price: 10,
      img: "./images/item-1.jpeg",
    },
    {
      id: 20,
      category: "İçecekler",
      subcategory: "Soğuk İçecekler",
      title: "Pepsi",
      desc: "Kendine özgü tadı ve enerjik ruhuyla özel Pepsi içeceğimiz, dinamik bir deneyim sunuyor. Kola tadının ve hafif karbonatlı ferahlığın birleştiği her bir yudum, damakta canlı ve canlandırıcı bir lezzet patlaması yaratıyor. İlk yudumda hissedilen bu tanıdık lezzet, içeceğiniz anı sadece bir keyif anı değil, aynı zamanda enerji dolu bir anıya dönüştürüyor. Pepsi içeceğimiz, hem lezzet hem de enerji arayanları dinamik bir lezzet yolculuğuna davet ediyor.",
      price: 10,
      img: "./images/item-1.jpeg",
    },
    {
      id: 21,
      category: "İçecekler",
      subcategory: "Soğuk İçecekler",
      title: "Meyve Suyu",
      desc: "Tutkulu bir doğa gezisine çıkıyormuş gibi hissetmeye hazır olun! Özel meyve sularımız, meyvelerin doğallığını ve renkliliğini bardağınıza taşıyor. Her bir yudum, taze meyve bahçelerinde yürüyormuşçasına canlı ve canlandırıcı bir lezzet sunuyor. İlk yudumda damakta açılan bu meyve şenliği, içeceğiniz anı sadece bir meyve suyu içimi değil, aynı zamanda meyve ağaçları arasında bir maceraya dönüştürüyor. Meyve sularımız, hem doğanın tazeliğini arayanları hem de sıradışı lezzetleri denemek isteyenleri benzersiz bir doğa yolculuğuna davet ediyor.",
      price: 10,
      img: "./images/item-1.jpeg",
    },
    {
      id: 22,
      category: "İçecekler",
      subcategory: "Soğuk İçecekler",
      title: "Niğde Gazozu",
      desc: "Anadolunun Gizemli İçeceği: Özel Niğde Gazozu  Gelenek ve lezzetin buluştuğu özel Niğde Gazozu, sizi tarihin derinliklerinde bir yolculuğa davet ediyor. Her bir yudum, taptaze doğal malzemelerin ve geleneksel tarifin izlerini taşıyor. İlk yudumda damakta hissedilen bu eşsiz tat, sadece bir içecek değil, aynı zamanda Anadolunun zengin kültürünün bir yansıması. Niğde Gazozunun benzersiz aroması ve ferahlığı, sizi hem geçmişe götürüyor hem de bugünkü anın tadını çıkarmaya davet ediyor. Bu özel içecek deneyimi, hem geleneksel lezzetlere meraklıları hem de farklı tatlar arayanları unutulmaz bir tat yolculuğuna çıkarıyor.",
      price: 10,
      img: "./images/item-1.jpeg",
    },
    {
      id: 23,
      category: "İçecekler",
      subcategory: "Soğuk İçecekler",
      title: "Soğuk Çaylar (Fuse Tea, Lipton ve Didi)",
      desc: "Bardağınızı Serinleten Tadlar: Özel Soğuk Çaylar  Taze bir serinlik ve çarpıcı lezzetlerle dolu özel soğuk çaylarımız, sizi ferahlatıcı bir lezzet macerasına davet ediyor. Her bir yudum, özenle seçilmiş çay yapraklarının ve doğal aromaların birleşimini taşıyor. İlk yudumda damakta açılan bu eşsiz tatlar, içeceğiniz anı sadece bir içim değil, aynı zamanda tatların ve aromaların büyülü dünyasında bir yolculuk anına dönüştürüyor. Fuse Teanin sofistike notaları, Liptonun klasik çay keyfi ve Didinin benzersiz karışımlarıyla tanıştığınız bu deneyim, hem çayın tutkunu olanları hem de yenilikçi tatlar arayanları ferahlatıcı bir lezzet serüvenine çıkarıyor.",
      price: 10,
      img: "./images/item-1.jpeg",
    },
    {
      id: 24,
      category: "İçecekler",
      subcategory: "Soğuk İçecekler",
      title: "Sade Soda",
      desc: "Doğanın İçeceği: Özel Sade Soda  Kristal berraklığı ve hafif karbonatlı ferahlığıyla özel sade soda içeceğimiz, saf doğanın bir yudumu gibidir. Her bir yudum, içeceğinizin temiz ve hafif tadını damakta bırakır. İlk yudumda hissedilen bu hafif lezzet, içeceğiniz anı sadece bir soda içimi değil, aynı zamanda doğanın arınmış ve canlandırıcı bir haline dönüştürür. Özel sade soda içeceğimiz, hem basit ve temiz bir tat arayanları hem de ferahlatıcı bir içecek isteyenleri saf ve hafif bir lezzet yolculuğuna davet ediyor.",
      price: 10,
      img: "./images/item-1.jpeg",
    },
    {
      id: 25,
      category: "İçecekler",
      subcategory: "Soğuk İçecekler",
      title: "Meyveli Soda",
      desc: "Meyve Bahçesinin İncisi: Özel Meyveli Soda  Taze meyve notalarının coşkusunu bardağınıza taşıyan özel meyveli soda içeceğimiz, ferahlamanın ve lezzetin mükemmel bir karışımını sunuyor. Her bir yudum, meyvelerin doğal tatlarının ve sodanın hafif karbonatlı dokusunun birleşimini taşıyor. İlk yudumda damakta açılan bu eşsiz tat, içeceğiniz anı sadece bir içim değil, aynı zamanda meyve bahçelerinde bir gezintiye dönüştürüyor. Meyveli soda içeceğimiz, hem meyve tadını arayanları hem de serin ve lezzetli bir içecek isteyenleri ferahlatıcı bir lezzet yolculuğuna davet ediyor.",
      price: 10,
      img: "./images/item-1.jpeg",
    },
    {
      id: 26,
      category: "İçecekler",
      subcategory: "Sıcak İçecekler",
      title: "Salep",
      desc: "Ruhunuzu Isıtan Lezzet: Özel Salep İçeceğimiz  Sıcacık bir kucaklama gibi, özel salep içeceğimiz sizi iç ısıtan bir deneyime davet ediyor. Salepin yoğun ve sıcak aroması, her bir yudumda damakta hoş bir tat bırakır. İlk yudumda hissedilen bu benzersiz lezzet, içeceğiniz anı sadece bir içim değil, aynı zamanda sıcak bir kahkaha ya da huzurlu bir sohbetle dolu bir anıya dönüştürür. Özel salep içeceğimiz, hem klasik bir tat arayanları hem de iç ısıtan bir içecekle kendi anılarını yaratmak isteyenleri sıcacık bir lezzet serüvenine davet ediyor.",
      price: 10,
      img: "./images/item-1.jpeg",
    },
    {
      id: 27,
      category: "İçecekler",
      subcategory: "Çaylar",
      title: "Ihlamur",
      desc: "Rahatlatıcı Bir Nefes: Özel Ihlamur İçeceğimiz  Doğanın hediyesi olan özel ıhlamur içeceğimiz, sizi huzurlu bir lezzet yolculuğuna çıkarıyor. Ihlamurun hafif ve rahatlatıcı aroması, her bir yudumda damakta huzurlu bir tat bırakır. İlk yudumda hissedilen bu sakinleştirici lezzet, içeceğiniz anı sadece bir içim değil, aynı zamanda rahat bir nefes alma anına dönüştürür. Özel ıhlamur içeceğimiz, hem geleneksel bir lezzet arayanları hem de doğanın sakinliğini bardağında bulmak isteyenleri huzurlu bir lezzet yolculuğuna davet ediyor.",
      price: 10,
      img: "./images/item-1.jpeg",
    },
    {
      id: 28,
      category: "İçecekler",
      subcategory: "Sıcak İçecekler",
      title: "Nane Limon",
      desc: "Tazeleyici ve Ferahlatıcı: Özel Nane Limon İçeceğimiz  Tatlı nanenin ferahlığını ve limonun canlandırıcı tadını bir araya getiren özel nane limon içeceğimiz, sıcak günlerin ve enerji dolu anların en iyi arkadaşıdır. Her bir yudum, nanenin serinliği ve limonun hafif asiditesinin mükemmel bir dengesini taşır. İlk yudumda damakta hissedilen bu canlandırıcı tat, içeceğiniz anı sadece bir içim değil, aynı zamanda taze bir esinti veya enerji dolu bir anıya dönüştürür. Özel nane limon içeceğimiz, hem ferahlatıcı bir lezzet arayanları hem de kendini enerjik hissetmek isteyenleri serinletici bir lezzet serüvenine davet ediyor.",
      price: 10,
      img: "./images/item-1.jpeg",
    },
    {
      id: 29,
      category: "İçecekler",
      subcategory: "Soğuk İçecekler",
      title: "Milkshake (Çilekli ve Çikolatalı)",
      desc: "Lezzet Şöleni: Özel Milkshake Çeşitlerimiz  Tatlı bir ziyafete hazır olun! Özel çilekli ve çikolatalı milkshake içeceklerimiz, damakta unutulmaz bir lezzet patlaması yaratıyor. Her bir yudum, taptaze çileğin ve yoğun çikolatanın eşsiz tadını taşıyor. İlk yudumda damakta açılan bu tatlar, içeceğiniz anı sadece bir içim değil, aynı zamanda tatlı bir kutlama veya keyifli bir anıya dönüştürüyor. Çilekli milkshakein canlılığı ve çikolatalı milkshakein yoğunluğuyla tanıştığınız bu deneyim, hem tatlı severleri hem de lezzetin büyülü dünyasını yaşamak isteyenleri muhteşem bir lezzet serüvenine davet ediyor.",
      price: 10,
      img: "./images/item-1.jpeg",
    },
    {
      id: 30,
      category: "Yiyecekler",
      subcategory: "Kahvaltı",
      title: "Serpme Kahvaltı",
      desc: "Zengin Bir Tat Festivali: Özel Serpme Kahvaltı  Lezzetlerin kucaklaştığı bir sofra hazırlayın! Özel serpme kahvaltı, çeşitliliğin ve taptaze lezzetlerin buluştuğu bir şölen sunuyor. Her bir tabak, peynirin yumuşaklığından zeytinin tazeliğine, reçelin tatlılığından taze sebzelerin canlılığına kadar her bir lezzeti taşıyor. İlk ısırıkta damakta açılan bu tatlar, kahvaltının sadece bir öğün olmadığını, aynı zamanda tüm bir lezzet festivali olduğunu anlatıyor. Özel serpme kahvaltı, hem geleneksel kahvaltıları sevenleri hem de farklı tatların birleştiği bir ziyafeti denemek isteyenleri lezzet dolu bir yolculuğa davet ediyor.",
      price: 10,
      img: "./images/item-1.jpeg",
    },
    {
      id: 31,
      category: "Yiyecekler",
      subcategory: "Kahvaltı",
      title: "Tost Çeşitleri",
      desc: "Tostun Yaratıcılığı: Özel Tost Çeşitleri  Tostlarla farklı bir tat deneyimi yaşamaya hazır olun! Özel tost çeşitlerimiz, damakta farklı lezzetleri bir araya getiriyor. Her bir ısırık, eşsiz malzemelerin uyumunu taşıyor. İlk ısırıkta hissedilen bu tatlar, tostun sadece bir ara öğün olmadığını, aynı zamanda yaratıcılığın ve lezzetin birleştiği bir serüven olduğunu anlatıyor. Siz de kendi damak zevkinize uygun tost çeşidini seçerek, özel bir tat yolculuğuna çıkmaya davetlisiniz.",
      price: 10,
      img: "./images/item-1.jpeg",
    },
    {
      id: 32,
      category: "Yiyecekler",
      subcategory: "Kahvaltı",
      title: "Gözleme Çeşitleri",
      desc: "Anadolunun Lezzet Haritası: Özel Gözleme Çeşitleri  Geleneksel tatların ve taptaze malzemelerin bir araya geldiği özel gözleme çeşitlerimiz, Anadolunun lezzetlerini sofranıza taşıyor. Her bir katman, anne elinin dokunuşunu ve özenle seçilen iç malzemelerin uyumunu taşıyor. İlk ısırıkta hissedilen bu lezzetler, gözlemenin sadece bir yemek olmadığını, aynı zamanda bir coğrafyanın ve kültürün tatlarını anlattığını gösteriyor. Siz de kendinize uygun gözleme çeşidini seçerek, özel bir lezzet yolculuğuna çıkmaya davetlisiniz.",
      price: 10,
      img: "./images/item-1.jpeg",
    },
    {
      id: 33,
      category: "Yiyecekler",
      subcategory: "Kahvaltı",
      title: "Köfte Ekmek",
      desc: "Tatlı ve Tuzlu Uyum: Özel Köfte Ekmek Çeşitleri  Lezzetin iki ucu bir araya geliyor! Özel köfte ekmek çeşitlerimiz, tatlı ve tuzlu notaların buluştuğu bir deneyim sunuyor. Her bir ısırık, köftenin lezzetini ve ekmekle tamamlayan tatları taşıyor. İlk ısırıkta hissedilen bu eşsiz uyum, köfte ekmeğin sadece bir atıştırmalık olmadığını, aynı zamanda farklı tatların harika bir kombinasyonunu ifade ettiğini anlatıyor. Özel köfte ekmek çeşitlerimiz, hem tatlı hem tuzlu lezzetleri bir araya getirmek isteyenleri hem de farklı tatların uyumunu denemek isteyenleri özel bir lezzet yolculuğuna davet ediyor.",
      price: 10,
      img: "./images/item-1.jpeg",
    },
    {
      id: 34,
      category: "Yiyecekler",
      subcategory: "Kahvaltı",
      title: "Patates Ekmek",
      desc: "Lezzetli Bir Serüven: Özel Patates Ekmek Çeşitleri  Patatesin sıcaklığı ve ekmekle uyumuyla dolu özel patates ekmek çeşitlerimiz, doyurucu ve lezzet dolu bir deneyim sunuyor. Her bir ısırık, patatesin yumuşaklığını ve ekmekle bütünleşen aromaları taşıyor. İlk ısırıkta damakta açılan bu tatlar, patates ekmeğin sadece bir yemek değil, aynı zamanda sıcaklığın ve lezzetin bir araya geldiği bir serüven olduğunu anlatıyor. Özel patates ekmek çeşitlerimiz, hem doyurucu hem de lezzetli bir yemek arayanları hem de farklı tatların uyumunu denemek isteyenleri özel bir lezzet yolculuğuna davet ediyor.",
      price: 10,
      img: "./images/item-1.jpeg",
    },
    {
      id: 35,
      category: "Yiyecekler",
      subcategory: "Kahvaltı",
      title: "Patso",
      desc: "Tatların Dansı: Özel Patso Çeşitleri  Lezzetli bir şölen başlıyor! Özel patso çeşitlerimiz, çeşitli malzemelerin ve tatların enfes bir kombinasyonunu sunuyor. Her bir ısırık, dengeli bir lezzet deneyimi taşıyor. İlk ısırıkta damakta açılan bu tatlar, patsonun sadece bir atıştırmalık değil, aynı zamanda tatların renkli bir dansını ifade ettiğini anlatıyor. Özel patso çeşitlerimiz, hem hızlı bir atıştırmalık arayanları hem de farklı tatların harmonisini denemek isteyenleri lezzet dolu bir yolculuğa davet ediyor.",
      price: 10,
      img: "./images/item-1.jpeg",
    },
    {
      id: 36,
      category: "Yiyecekler",
      subcategory: "Kahvaltı",
      title: "Sıcak Tabak",
      desc: "İçerik: Patates, Sigara böreği, soğan halkası.Sıcak Tabakta Lezzet Şöleni: Özel İçerik  Sıcak tabak içeriğimiz, damaklarda unutulmaz bir lezzet patlaması yaratıyor. Taze patateslerin çıtır çıtır tadı, nefis sigara böreğinin kıyır kıyır dokusu ve çıtır soğan halkalarının hafif baharatlı aroması bir araya geliyor. Her bir ısırık, bu özel lezzetlerin ve malzemelerin uyumunu taşıyor. İlk ısırıkta damakta açılan bu tatlar, sıcak tabağın sadece bir yemek değil, aynı zamanda farklı malzemelerin enfes bir dansını ifade ettiğini anlatıyor. Sıcak tabak içeriğimiz, hem çeşitli lezzetlerle dolu bir yemek arayanları hem de farklı tatların uyumunu denemek isteyenleri lezzet dolu bir yolculuğa davet ediyor.",
      price: 10,
      img: "./images/item-1.jpeg",
    },
  ];
  export default menu;
  